### ISSUE TITLE
Excessive memory use

### ISSUE THREAD

**Issue by icbm-iupui** [icbm-iupui/volumetric-tissue-exploration-analysis#12]
When using image datasets larger than 5 GB, the memory use seems excessive-quickly fills up 128 GB.  This needs to be addressed to ease the analysis of high res image volumes.

**Comment by winfrees** [comment]
This will not be addressed in 0.5.2 or 0.7.  Version 1.0 solves this to some degree.  VTEA now requires ~3x the original dataset size.  Future fixes may include changing the underlying datatype for the image file.  This will be pushed to a feature request in versions > 1.0.
