### ISSUE TITLE
FeatureFrame improvement

### ISSUE THREAD

**Issue by icbm-iupui** [icbm-iupui/volumetric-tissue-exploration-analysis#37]
Make the FeatureFrame smarter.  

1) Allow previous feature settings to persist without re-running. 

2) Make connection between Feature definition and popupmenu strings clearer- ex. manage the rerunning of a ward for 5 clusters giving the same entry in the popupmenu

3) Make connection between Feature definition and outputs clearer-dendogram titles?

**Comment by icbm-iupui** [comment]
Could split this issue into multiple issues.

**Comment by icbm-iupui** [comment]
Yeah, adding the name of the underlying data would be ideal, however, i understand then you’d have to pass the string through an event or some other mechanism from the explorer.  I think just a title that links it to the method like:  “Ward Clustering”.  The number of clusters would be nice to indicate, but only if we could colorize the dendrogram to reflect the clusters.  Otherwise the dendrogram always looks the same.

Seth


Seth Winfree
Department of Medicine, Division of Nephrology
Department of Cellular and Integrative Physiology
Indiana University School of Medicine
950 W Walnut St, R2-202
Indianapolis, IN 46202-5116





On Dec 20, 2018, at 4:25 PM, drewnutt <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure what you mean by 1.

What would you like to be in the dendrogram titles? I could easily add in the type of clustering, but adding in the names of the data that are being manipulated would be more complex.

**Comment by icbm-iupui** [comment]
For 1.  If the method has been already run and the values entered into the Explorer it would be better if the user couldn't run it again-we could set a flag to prevent rerunning by the FeatureProcessor.  Let me look at it again,  I'd like the segmentation to behave the same way.

**Comment by drewnutt** [comment]
I have addressed 2 and 3 with my most recent push.  However, the size of the JComboBoxes needs to update in MicroExplorer so you can see the timestamp I added to the name of the feature within the combo boxes.

**Comment by icbm-iupui** [comment]
For the JComboBoxes I added a mouseover text that presents the full name.  This could be used in the future if we wanted to add more of a description to the "features" that are measured automatically.

**Comment by icbm-iupui** [comment]
I think with the addition of the timestamp, we don't need to worry about item one.  The individual features are enumerated by the time stamp.
