### ISSUE TITLE
Inconsistent overlay behavior ImageJ

### ISSUE THREAD

**Issue by icbm-iupui** [icbm-iupui/volumetric-tissue-exploration-analysis#44]
The overlay mechanism in ImageJ is behaving bizarrely on a fresh run with Fiji

**Comment by icbm-iupui** [comment]
This bug appears to be a difference in single channel vs multichannel segmentation.  Maybe this is how the BufferedImage is being defined.

**Comment by winfrees** [comment]
This has been reworked with the new tabulated gate interface.  We may need to revisit this.
