### ISSUE TITLE
Segmentation using LSConnect throws error

### ISSUE THREAD

**Issue by surajkhochare** [icbm-iupui/volumetric-tissue-exploration-analysis#47]
The steps are as follows:
1) Open VTEA and load image in first workflow.
2) Process the first image and perform segmentation using LSConnect.
3) Workflow_1 or Image_0 completes segmentation successfully.
4) Now, add another workflow and load image after 3D Median filtering.
5) Process this image and go for segmentation.
6) The error can be seen in logs after clicking 'Find Objects' to perform segmentation.

**Comment by surajkhochare** [comment]
I think the issue is because of loading an image with single channel in VTEA. If we load a multiple channel image, the segmentation is completed successfully but it takes lot of time.

**Comment by surajkhochare** [comment]
This process is working fine if we use Connect3D instead of LSConnect3D.

**Comment by icbm-iupui** [comment]
Commit  55689d8 fixed this issue.
