### ISSUE TITLE
.obx loading from old 1.0 alpha version faulty

### ISSUE THREAD

**Issue by icbm-iupui** [icbm-iupui/volumetric-tissue-exploration-analysis#51]
**Describe the bug**
obx files created in VTEA 1.0 alpha from, 1c32f25, cannot be loaded in the commit:

f5f9aba71b7c334a7f916847efb13889dd160ccc

Drew had centralized the file operations to a central class (), could this be the source of the problem?

**Comment by winfrees** [comment]
This was caused by not insisting on a Serialization ID in the microobject class.  To fix a work around need to be implemented to open old/early .obx files.

**Comment by winfrees** [comment]
We maintain archival versions of VTEA to ensure obxs created with this alpha version remain accessible.  If required this issue could be reopened to build a workflow for upgrading the limited number of obxs that were faulty.
