### ISSUE TITLE
Gaussian Mixtures

### ISSUE THREAD

**Issue by winfrees** [icbm-iupui/volumetric-tissue-exploration-analysis#55]
Gaussian mixtures  without BIC or AIC only reports 3 clusters irrespective of requested cluster number.  

1.  Process a volume (i.e. AQ-Test)
2. Perform processing as normal
3. Perform segmentation with LS 3D Connect or 3DConnect
4. Add features and process for Gaussian Mixtures without BIC or AIC
4. Only 3 clusters will report irrespective of requested cluster number

**Expected behavior**
more than 3 clusters!

**Comment by drewnutt** [comment]
c5bc88ba8884b21a9b66c2901ec2dc17973423c6 Should fix this issue

**Comment by winfrees** [comment]
c5bc88b, fixes this.  closing issue.
