### ISSUE TITLE
Importing segmentation results from other sources.  

### ISSUE THREAD

**Issue by matfallet** [icbm-iupui/volumetric-tissue-exploration-analysis#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by winfrees** [comment]
Sorry for the delay.  The current climate is stretching resources!  Thank you for your interest in VTEA.  Right now VTEA is designed to segment, generate objects internally, measures and then provides the scatter interface.  If I understand correctly, you'd like to  import ROIs (imagej?) and a set of measurements also from imageJ and use the gating and mapping back interface?  Cheers.  Thanks for the interest.

**Comment by matfallet** [comment]
Dear Seth,

Yes that is exact, I am not interested by the segmentation only by the scatterplot and visulaisation back to the image.

Is there a way to implement thsi part in your program, do you want my roi.zip and my image to try  ?

Thanks,

Mathieu Fallet

________________________________
De : Seth Winfree <notifications@github.com>
Envoyé : mardi 28 avril 2020 03:15:44
À : icbm-iupui/volumetric-tissue-exploration-analysis
Cc : Mathieu FALLET; Author
Objet : Re: [icbm-iupui/volumetric-tissue-exploration-analysis] Dear developper, I am very interested by your project. I would like to test it, do you have any documentation ? For example, I have an image with ROI.zip and measurents(ID, mean cell type 1, mean ...


Sorry for the delay. The current climate is stretching resources! Thank you for your interest in VTEA. Right now VTEA is designed to segment, generate objects internally, measures and then provides the scatter interface. If I understand correctly, you'd like to import ROIs (imagej?) and a set of measurements also from imageJ and use the gating and mapping back interface? Cheers. Thanks for the interest.

-

**Comment by icbm-iupui** [comment]
Mathieu,

?

There are a number of entry points/methods we could use.  The simplest would probably be to write an import class that interacts with "MicroExplorer" (https://github.com/icbm-iupui/volumetric-tissue-exploration-analysis/blob/master/src/main/java/vteaexploration/MicroExplorer.java).  I'd probably convert the existing import class structure to a more generalizable approach and move from there.  I'm going to combine your request (56) with another (57) and start working through the implementation.


Thanks again for your interest,


Seth

________________________________

**Comment by winfrees** [comment]
To summarize we'd like to implement importing of segmentation results from other sources into the MicroExplorer functionality:

1)import segmentation from Integer images with or without repeating indices (8,16,32 bit, re #57 )
2)import ROI based segmentations  (imageJ, etc)
2)import existing measurements keyed to indices (must be unique, re #57 )
3)perform measurements on imported segmentations

**Comment by matfallet** [comment]
ok great, we are working on the same subject using R but would be great to have a plugin that we can use in Image J that can make live scatterplot and look directly the dots in the scatterplots on ROI in the image.

Best, Mathieu


________________________________
De : Seth Winfree <notifications@github.com>
Envoyé : samedi 2 mai 2020 16:49:12
À : icbm-iupui/volumetric-tissue-exploration-analysis
Cc : Mathieu FALLET; Author
Objet : Re: [icbm-iupui/volumetric-tissue-exploration-analysis] Importing segmentation results from other sources. (#56)


To summarize we'd like to implement importing of segmentation results from other sources into the MicroExplorer functionality:

1)import segmentation from Integer images with or without repeating indices (8,16,32 bit, re #57<https://github.com/icbm-iupui/volumetric-tissue-exploration-analysis/issues/57> )
2)import ROI based segmentations (imageJ, etc)
2)import existing measurements keyed to indices (must be unique, re #57<https://github.com/icbm-iupui/volumetric-tissue-exploration-analysis/issues/57> )
3)perform measurements on imported segmentations

-

**Comment by winfrees** [comment]
The import of ImageJ Rois (via an embedded RoiManager) is now possible in the VTEA workflow.  This is a partial completion of this issue/feature request.  Reference: see 15373b6 in the RengLUT branch.  
![RoiBasedSegmentation_092320](https://user-images.githubusercontent.com/3803929/94074593-9b0f1e80-fdc7-11ea-9fcd-002d558568db.png)

**Comment by winfrees** [comment]
Recap and status on issues:

1)import segmentation from Integer images with or without repeating indices (8,16,32 bit, re #57 )
**in-progress**
2)import ROI based segmentations (imageJ, etc)
**completed**  This is for ImageJ1 Rois.  Looking into ImageJ2/imglib2 and cellprofiler
3)import existing measurements keyed to indices (must be unique, re #57 )
**completed**   This has been done for awhile, use the import CSV button on the Explorer window
4)import images for mapping and measurements
**queued**
5)perform measurements on imported images using these segmentations
**in-progress**

**Comment by winfrees** [comment]
Finalized import of segmented nuclei from a segmentation map as indicated in 3da0ef5.  This may fail for unusually large objects but is functional for fields of nuclei at 20-30x.  These exceptions will be handled in a future change.

**Comment by winfrees** [comment]
Recap and status on issues:

1)import segmentation from Integer images with or without repeating indices (8,16,32 bit, re #57 )
**completed**
2)import ROI based segmentations (imageJ, etc)
**completed**  This is for ImageJ1 Rois.  Looking into ImageJ2/imglib2 and cellprofiler
3)import existing measurements keyed to indices (must be unique, re #57 )
**completed**   This has been done for awhile, use the import CSV button on the Explorer window
4)import images for mapping and measurements
**moving to a new issue**-this requires mostly gui changes and working with (5)
5)perform measurements on imported images using these segmentations
**moving to a new issue**-this requires the import of image data and passing through the MeasurementProcessor.

Sub-issues 4 and 5 are being moved to issue #59.

**Comment by winfrees** [comment]
@matfallet , if there is functionality missing to address #57, please let me know.  Otherwise I'd like to close this issue.

@schienstockd, the ability to import a segmentation map has been implemented (#56).  Let me know if the functionality described in 3da0ef5 addresses this feature request.

**Comment by schienstockd** [comment]
I'm not sure how this works now. Could you give a small tutorial to your solution?

What I have is an image called "seg" which is a 32-bit TIF where each segmented objects has a unique ID.
The intensities are then taken from a multi-channel image called "raw".

Is that possible to combine with this?

**Comment by winfrees** [comment]
These functionality have been implemented.  A demonstration will be presented [here](https://vtea.wiki/sketches.html#importing-segmentation) within the next week.
