### ISSUE TITLE
Importing segmention

### ISSUE THREAD

**Issue by schienstockd** [icbm-iupui/volumetric-tissue-exploration-analysis#57]
I have an image that is already segmented ie/ I have a TIFF with individual objects.

I would like to import the object TIFF and the fluorescence image to gate on cells.

The segmentation pipeline that I used could not be done with the processing function in your plugin. It is a bit more customised.

**Comment by winfrees** [comment]
Thank you for your interest in VTEA.  How are your objects defined-as a color-coded (RGB) or integer images?

**Comment by schienstockd** [comment]
They are 32-bit labelled integer images. Every object has a unique ID. Then I would like to plot and gate based on the intensity for every object for every channel from another 6-channel image.

**Comment by winfrees** [comment]
Great.  A second request, (#56) is asking for nearly the same thing.  I'm going to combine your two requests.  I think this is critical functionality I can spend some time on.
