### ISSUE TITLE
3D view button

### ISSUE THREAD

**Issue by icbm-iupui** [icbm-iupui/volumetric-tissue-exploration-analysis#6]
Unpredictable behavior of 3D button in Explorer window

It will work the first time but then fails to generate a result a second time.  The console is throwing a NullPointerException when assigning the stack.  Is this related to the closing of images?

**Comment by icbm-iupui** [comment]
Fixed in 1.0 branch FeatureService, still active for 0.5.2

**Comment by icbm-iupui** [comment]
This is addressed in v0.7b

**Comment by winfrees** [comment]
This issue has been addressed.  Closing.
