### ISSUE TITLE
user manual 

### ISSUE THREAD

**Issue by matfallet** [icbm-iupui/volumetric-tissue-exploration-analysis#60]
Dear Seth, 

Thanks for implementation of ROI import. 
Could you describe me how to import the ROI (COI) on my image. The second point is that I have no idea when I do the a scatterplot to see the Q1 and Q4 dots on my image ? It would be great to have a documentation and a  video to explain to use your plugin.
Thanks, 

Mathieu

**Comment by matfallet** [comment]
Ok I can load a gate on my image by clicking on that gate but how to visualize two gates ?

![Clipboard](https://user-images.githubusercontent.com/41480459/95763022-cdb58400-0cae-11eb-82ba-50076ab2da7d.jpg)

**Comment by winfrees** [comment]
Mathieu,

It looks like you are using v0.7.  The features you requested (images rows) and others(multiple highlights) are in the alpha version on the branch, [ReEngineerLUTImplementation](https://github.com/icbm-iupui/volumetric-tissue-exploration-analysis/tree/ReEngineerLUTImplementation).

1) If you are comfortable building the plugin jar from a maven build in NetBeans or Eclipse, that might be easiest route for getting up and running both in terms of compiling as well as collecting all the dependencies.  

2) I'll put together an alpha release that will incorporate the ROI import in the next couple days if that doesn't work.

3) Documentation...  That is a part of the manuscript, it is coming.

4) I'm almost through drafting the manuscript, at which point there will be a BioArchives version and beta version referenced above will be become available through the ImageJ updater

Thanks for your interest, and nice work with  your implementation,  looks great!

Seth

**Comment by winfrees** [comment]
Im going to reopen this issue as it is critical for on-going use.  It may be expanded and bifurcated to meet documentation needs.

**Comment by winfrees** [comment]
@matfallet, The prerelease with IMAGEJ1.0 ROIs is available (611c548).  There may be dependencies that are needed, let me know if you have any trouble.  

https://github.com/icbm-iupui/volumetric-tissue-exploration-analysis/releases

**Comment by matfallet** [comment]
ok great, do you have a bug with czi image (300Mo, 6 channels)? The 1.0 version do not load my image (message : image loading ...). Thanks

**Comment by matfallet** [comment]
it doesn't work (load image) also with  a tif image (4Mo) ) in 2D with 4 channels with the release v1.0 alpha r5. I just put plugin in the plugin folder.
Best

**Comment by winfrees** [comment]
This is probably a missing dependency during VTEA plugin loading.  I've added the necessary dependencies in a .zip file with the release.  I'd also reinstall the plugin as I removed a dependency for a rather large .jar file.  Attached image shows VTEA running with my test volume.

![Clipboard](https://user-images.githubusercontent.com/3803929/95883085-8085f080-0d48-11eb-81a3-9bcb7558d70d.png)

**Comment by winfrees** [comment]
The website to begin to address this issue is being constructed at:  [vtea.wiki](https://vtea.wiki).  This site will cover, installation, sketches demonstrating use with access to demonstration data, and FAQs and references.

**Comment by winfrees** [comment]
Closing this issue as the website is ongoing.  Specific requests for topics to cover on the website can be reopened as an issue [here](https://github.com/icbm-iupui/volumetric-tissue-exploration-analysis/issues/60) or at [VTEA-site](https://github.com/winfrees/vtea-site/blob/main/sketches.md).
