### ISSUE TITLE
Gate manager

### ISSUE THREAD

**Issue by Daria4ML** [icbm-iupui/volumetric-tissue-exploration-analysis#76]
Currently, in Gate Manager, wanting to access a gate (and x-y axis feature setup) user should change the x and y axis to the ones that reflect the setup when the gate was drawn. 

A helpful feature (and time saver) would be the option to click on the gate within the gate manager to then automatically change the x and y axis to those associated with the gate.

**Comment by winfrees** [comment]
@Daria4ML, this is a great idea, added this functionality. This has been addressed/fixed in the branch: https://github.com/icbm-iupui/volumetric-tissue-exploration-analysis/tree/GUIImprovements.  A new release version will be made available and the FIJI update-site updated with this fix.

**Comment by winfrees** [comment]
Functionality added in #79 and released in[ v1.0.3](https://github.com/icbm-iupui/volumetric-tissue-exploration-analysis/commit/5b720dbff3a65fd91e07abba46bc451a42c7435c)
