### ISSUE TITLE
Window always on top

### ISSUE THREAD

**Issue by Daria4ML** [icbm-iupui/volumetric-tissue-exploration-analysis#77]
Right now, the VTEA plots are always on top. 

Sometimes this makes working within small space challenging, and pop-up menus/windows can hide behind the plot. 

Having the option to turn off or on the feature of the plot staying always on top would be very helpful.

**Comment by winfrees** [comment]
@Daria4ML.  Which plots are you referring to?  The main window or the heatmap and violin plots?

**Comment by Daria4ML** [comment]
@winfrees The main segmentation plot and the associated windows like gate manager.

**Comment by winfrees** [comment]
@Daria4ML Currently, the explorer and gate manager windows (with the plot) are not setup as an "always ontop."  It may be that some dialogs/popups/menus are not always brought to the front?  Do you recall which dialogs/popups/menus were obscured by the explorer?

**Comment by winfrees** [comment]
Any additional concerns with windows set to "Always on top"?

**Comment by winfrees** [comment]
Great! I'm going to close this issue for now.  Thanks.
