### ISSUE TITLE
Scroll down menus in the plot panel

### ISSUE THREAD

**Issue by Daria4ML** [icbm-iupui/volumetric-tissue-exploration-analysis#82]
Currently in the OBX files, once new features are added, they are being displayed at the end of the list within the scroll down menu for X and Y axis and Color. One has to scroll down quite a bit sometimes to find the new feature of interest.

It would be helpful if the new features were added on top of the scroll down menu - this allows for quick changes of newly selected features. 

Thank you!

**Comment by winfrees** [comment]
Fixed in latest commit @[c647f22](https://github.com/icbm-iupui/volumetric-tissue-exploration-analysis/commit/c647f221454f78747ca1cd5ea6ae68ddc4143b17), as noted above.  Thanks.
