### ISSUE TITLE
Violin plot "Export" function not working

### ISSUE THREAD

**Issue by Daria4ML** [icbm-iupui/volumetric-tissue-exploration-analysis#87]
After generating a violin plot - the Export feature does not work - it does not actually generate a saved file. 

in VTEA 1.1.6 and VTEA 1.1.8.

**Comment by winfrees** [comment]
I'll look into this.  It looks like a text parsing error.  Should be fixed quickly.  In the interim there is a low res version in .\Fiji.app\VTEA\plots that you can use.

**Comment by Daria4ML** [comment]
Thank you - no hurry. I use the snipping tool in the meantime.

**Comment by winfrees** [comment]
Should be resolved as of 269dc7a.  This will be included in the next update, v1.1.9.

**Comment by Daria4ML** [comment]
Awesome! Thank you!
